# Staging Environment Configuration Patches
# Specific overrides for staging environment

apiVersion: v1
kind: ConfigMap
metadata:
  name: fusion-bitcoin-config
data:
  # Application configuration for staging
  NODE_ENV: "staging"
  APP_NAME: "fusion-bitcoin-bridge"
  APP_VERSION: "staging-v1.0.0"
  LOG_LEVEL: "info"
  
  # Service ports
  RELAYER_PORT: "3000"
  RESOLVER_PORT: "3001" 
  FRONTEND_PORT: "3002"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "9091"
  
  # Network configuration for staging
  ETH_NETWORK: "goerli"
  BTC_NETWORK: "testnet"
  ETH_CONFIRMATION_BLOCKS: "3"
  BTC_CONFIRMATION_BLOCKS: "2"
  
  # Database configuration for staging (AWS RDS)
  DB_TYPE: "postgresql"
  DB_HOST: "fusion-bitcoin-staging-db.us-west-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "fusion_bitcoin_staging"
  DB_SSL: "true"
  DB_POOL_MIN: "5"
  DB_POOL_MAX: "20"
  DB_CONNECTION_TIMEOUT: "30000"
  DB_QUERY_TIMEOUT: "15000"
  
  # Redis configuration for staging (AWS ElastiCache)
  REDIS_HOST: "fusion-bitcoin-staging-redis.abc123.cache.amazonaws.com"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_KEY_PREFIX: "fusion:staging:"
  REDIS_TTL_DEFAULT: "3600"
  
  # Security configuration for staging
  HTTPS_ENABLED: "true"
  CORS_ENABLED: "true"
  CORS_ORIGINS: "https://staging.fusion-bitcoin.1inch.io,https://staging-api.fusion-bitcoin.1inch.io"
  RATE_LIMITING_ENABLED: "true"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  AUTHORIZATION_ENABLED: "true"
  
  # Monitoring configuration for staging
  METRICS_ENABLED: "true"
  HEALTH_CHECK_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"
  PROMETHEUS_ENDPOINT: "/metrics"
  SENTRY_ENABLED: "true"
  SENTRY_ENVIRONMENT: "staging"
  
  # Backup configuration for staging
  BACKUP_ENABLED: "true"
  BACKUP_SCHEDULE: "0 2 * * *"
  BACKUP_RETENTION_DAYS: "7"
  S3_BACKUP_BUCKET: "fusion-bitcoin-staging-backups"
  
  # Feature flags for staging
  ADVANCED_TRADING_ENABLED: "true"
  NOTIFICATIONS_ENABLED: "true"
  DARK_MODE_ENABLED: "true"
  ANALYTICS_ENABLED: "true"
  DEBUG_MODE_ENABLED: "false"
  
  # AWS specific configuration
  AWS_REGION: "us-west-2"
  AWS_S3_BUCKET: "fusion-bitcoin-staging-assets"
  AWS_CLOUDFRONT_DOMAIN: "staging-cdn.fusion-bitcoin.1inch.io"
  
  # External API configuration
  ETH_RPC_TIMEOUT: "10000"
  BTC_RPC_TIMEOUT: "15000"
  BLOCKCHAIN_SYNC_INTERVAL: "30000"
  
  # Performance tuning for staging
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_TIMEOUT: "30000"
  KEEPALIVE_TIMEOUT: "5000"
  
  # Logging configuration
  LOG_FORMAT: "json"
  LOG_MAX_FILES: "10"
  LOG_MAX_SIZE: "10m"
  ACCESS_LOG_ENABLED: "true"
  ERROR_LOG_ENABLED: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: fusion-bitcoin-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:123456789012:certificate/staging-cert-id"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3002
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3002
    protocol: TCP
  - name: api
    port: 8080
    targetPort: 3000
    protocol: TCP
  selector:
    app: fusion-bitcoin-bridge
    component: frontend

---
# HorizontalPodAutoscaler for staging
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fusion-bitcoin-relayer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fusion-bitcoin-relayer
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fusion-bitcoin-resolver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fusion-bitcoin-resolver
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fusion-bitcoin-relayer-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fusion-bitcoin-bridge
      component: relayer

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fusion-bitcoin-resolver-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fusion-bitcoin-bridge
      component: resolver