# Kustomization for Local Environment
# Manages environment-specific configurations for local development

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fusion-bitcoin-local
  annotations:
    config.kubernetes.io/local-config: "true"

# Base resources
resources:
  - ../../base

# Namespace
namespace: fusion-bitcoin-local

# Name prefix for all resources
namePrefix: local-

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: fusion-bitcoin-bridge
  app.kubernetes.io/instance: local
  app.kubernetes.io/component: infrastructure
  app.kubernetes.io/part-of: fusion-bitcoin
  app.kubernetes.io/managed-by: kustomize
  environment: local

# Common annotations
commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  config.kubernetes.io/origin: |
    path: infrastructure/kubernetes/environments/local/kustomization.yaml

# Images with local tags
images:
  - name: registry.example.com/fusion-bitcoin-relayer
    newTag: local-latest
  - name: registry.example.com/fusion-bitcoin-resolver
    newTag: local-latest
  - name: registry.example.com/fusion-bitcoin-frontend
    newTag: local-latest

# Resource patches for local environment
patches:
  # Reduce resource requirements for local development
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: fusion-bitcoin-relayer
  
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: fusion-bitcoin-resolver
  
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: fusion-bitcoin-frontend

  # Reduce resource requests for local
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
    target:
      kind: Deployment

  # Disable PostgreSQL StatefulSet for local (use external DB)
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      kind: StatefulSet
      name: fusion-bitcoin-postgres

  # Disable Redis Deployment for local (use external Redis)
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      kind: Deployment
      name: fusion-bitcoin-redis

# ConfigMap patches for local environment
patchesStrategicMerge:
  - local-config.yaml

# Generate ConfigMap for local-specific configuration
configMapGenerator:
  - name: fusion-bitcoin-local-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - METRICS_ENABLED=false
      - HEALTH_CHECK_ENABLED=true
    options:
      disableNameSuffixHash: true

# Generate Secret for local development
secretGenerator:
  - name: fusion-bitcoin-local-secrets
    literals:
      - DB_PASSWORD=localdev123
      - REDIS_PASSWORD=""
      - JWT_SECRET=local-jwt-secret-key-for-development-only
    type: Opaque
    options:
      disableNameSuffixHash: true

# Transformers
transformers:
  # Add local-specific labels
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: local-labels
    labels:
      deployment.environment: local
      cost-center: development
    fieldSpecs:
      - path: metadata/labels
        create: true