# Local Environment Configuration Patches
# Specific overrides for local development environment

apiVersion: v1
kind: ConfigMap
metadata:
  name: fusion-bitcoin-config
data:
  # Application configuration for local
  NODE_ENV: "development"
  APP_NAME: "fusion-bitcoin-bridge"
  APP_VERSION: "local-dev"
  LOG_LEVEL: "debug"
  
  # Service ports (same as base)
  RELAYER_PORT: "3000"
  RESOLVER_PORT: "3001" 
  FRONTEND_PORT: "3002"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "9091"
  
  # Network configuration for local
  ETH_NETWORK: "goerli"
  BTC_NETWORK: "testnet"
  ETH_CONFIRMATION_BLOCKS: "1"
  BTC_CONFIRMATION_BLOCKS: "1"
  
  # Database configuration for local (external)
  DB_TYPE: "postgresql"
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "fusion_bitcoin_local"
  DB_SSL: "false"
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  DB_CONNECTION_TIMEOUT: "30000"
  DB_QUERY_TIMEOUT: "15000"
  
  # Redis configuration for local (external)
  REDIS_HOST: "host.docker.internal"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_KEY_PREFIX: "fusion:local:"
  
  # Security configuration (relaxed for local)
  HTTPS_ENABLED: "false"
  CORS_ENABLED: "true"
  RATE_LIMITING_ENABLED: "false"
  AUTHORIZATION_ENABLED: "false"
  
  # Monitoring configuration
  METRICS_ENABLED: "false"
  HEALTH_CHECK_ENABLED: "true"
  PROMETHEUS_ENABLED: "false"
  SENTRY_ENABLED: "false"
  
  # Backup configuration (disabled for local)
  BACKUP_ENABLED: "false"
  
  # Feature flags for local development
  ADVANCED_TRADING_ENABLED: "true"
  NOTIFICATIONS_ENABLED: "false"
  DARK_MODE_ENABLED: "true"
  ANALYTICS_ENABLED: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: fusion-bitcoin-loadbalancer
spec:
  type: NodePort  # Change from LoadBalancer to NodePort for local
  ports:
  - name: http
    port: 80
    targetPort: 3002
    nodePort: 30080
    protocol: TCP
  selector:
    app: fusion-bitcoin-bridge
    component: frontend