/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EscrowDstInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PUBLIC_WITHDRAW_DELAY"
      | "amount"
      | "canPublicWithdraw"
      | "canRedeem"
      | "canRefund"
      | "deposit"
      | "depositTimestamp"
      | "depositor"
      | "emergencyRecover"
      | "getDetails"
      | "initialize"
      | "isRedeemed"
      | "isRefunded"
      | "orderId"
      | "publicWithdraw"
      | "redeem"
      | "refund"
      | "safetyDeposit"
      | "secretHash"
      | "timelock"
      | "token"
      | "withdrawer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EscrowCreated" | "Redeemed" | "Refunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PUBLIC_WITHDRAW_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "amount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canPublicWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canRedeem",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "canRefund", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "depositor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyRecover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isRedeemed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRefunded",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "orderId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "redeem", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "safetyDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "secretHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PUBLIC_WITHDRAW_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "amount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canPublicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canRedeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canRefund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRecover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDetails", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRedeemed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRefunded", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orderId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safetyDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "secretHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawer", data: BytesLike): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    token: AddressLike,
    amount: BigNumberish,
    secretHash: BytesLike,
    timelock: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    token: string,
    amount: bigint,
    secretHash: string,
    timelock: bigint
  ];
  export interface OutputObject {
    orderId: string;
    token: string;
    amount: bigint;
    secretHash: string;
    timelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    secret: BytesLike,
    redeemer: AddressLike
  ];
  export type OutputTuple = [orderId: string, secret: string, redeemer: string];
  export interface OutputObject {
    orderId: string;
    secret: string;
    redeemer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [orderId: BytesLike, refundee: AddressLike];
  export type OutputTuple = [orderId: string, refundee: string];
  export interface OutputObject {
    orderId: string;
    refundee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowDst extends BaseContract {
  contractName: "EscrowDst";

  connect(runner?: ContractRunner | null): EscrowDst;
  waitForDeployment(): Promise<this>;

  interface: EscrowDstInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PUBLIC_WITHDRAW_DELAY: TypedContractMethod<[], [bigint], "view">;

  amount: TypedContractMethod<[], [bigint], "view">;

  canPublicWithdraw: TypedContractMethod<
    [secret: BytesLike],
    [boolean],
    "view"
  >;

  canRedeem: TypedContractMethod<[secret: BytesLike], [boolean], "view">;

  canRefund: TypedContractMethod<[], [boolean], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositTimestamp: TypedContractMethod<[], [bigint], "view">;

  depositor: TypedContractMethod<[], [string], "view">;

  emergencyRecover: TypedContractMethod<[], [void], "nonpayable">;

  getDetails: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        _orderId: string;
        _token: string;
        _amount: bigint;
        _depositor: string;
        _withdrawer: string;
        _secretHash: string;
        _timelock: bigint;
        _safetyDeposit: bigint;
        _isRedeemed: boolean;
        _isRefunded: boolean;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _orderId: BytesLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _depositor: AddressLike,
      _withdrawer: AddressLike,
      _secretHash: BytesLike,
      _timelock: BigNumberish,
      _safetyDeposit: BigNumberish
    ],
    [void],
    "payable"
  >;

  isRedeemed: TypedContractMethod<[], [boolean], "view">;

  isRefunded: TypedContractMethod<[], [boolean], "view">;

  orderId: TypedContractMethod<[], [string], "view">;

  publicWithdraw: TypedContractMethod<
    [secret: BytesLike],
    [void],
    "nonpayable"
  >;

  redeem: TypedContractMethod<[secret: BytesLike], [void], "nonpayable">;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  safetyDeposit: TypedContractMethod<[], [bigint], "view">;

  secretHash: TypedContractMethod<[], [string], "view">;

  timelock: TypedContractMethod<[], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  withdrawer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PUBLIC_WITHDRAW_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canPublicWithdraw"
  ): TypedContractMethod<[secret: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canRedeem"
  ): TypedContractMethod<[secret: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canRefund"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyRecover"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDetails"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        _orderId: string;
        _token: string;
        _amount: bigint;
        _depositor: string;
        _withdrawer: string;
        _secretHash: string;
        _timelock: bigint;
        _safetyDeposit: bigint;
        _isRedeemed: boolean;
        _isRefunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _orderId: BytesLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _depositor: AddressLike,
      _withdrawer: AddressLike,
      _secretHash: BytesLike,
      _timelock: BigNumberish,
      _safetyDeposit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isRedeemed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRefunded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "orderId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publicWithdraw"
  ): TypedContractMethod<[secret: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[secret: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safetyDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "secretHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(bytes32,address,uint256,bytes32,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "Redeemed(bytes32,bytes32,address)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "Refunded(bytes32,address)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
  };
}
